// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwkkPSsq_elg37RGwx4Ifi3R7FErMJeg',
    appId: '1:283681334251:web:5c85c7ceb51d410b19efae',
    messagingSenderId: '283681334251',
    projectId: 'studywithgary-33612',
    authDomain: 'studywithgary-33612.firebaseapp.com',
    storageBucket: 'studywithgary-33612.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdntCjxQd8MUWymejvekxSbVKsjSo60h8',
    appId: '1:283681334251:android:393b70cf5185b12b19efae',
    messagingSenderId: '283681334251',
    projectId: 'studywithgary-33612',
    storageBucket: 'studywithgary-33612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqJEKIINxcQj_b4_dNCy1G2fxIt5djPM',
    appId: '1:283681334251:ios:8750b9c625bff3ea19efae',
    messagingSenderId: '283681334251',
    projectId: 'studywithgary-33612',
    storageBucket: 'studywithgary-33612.firebasestorage.app',
    iosBundleId: 'com.example.studywithgary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqJEKIINxcQj_b4_dNCy1G2fxIt5djPM',
    appId: '1:283681334251:ios:8750b9c625bff3ea19efae',
    messagingSenderId: '283681334251',
    projectId: 'studywithgary-33612',
    storageBucket: 'studywithgary-33612.firebasestorage.app',
    iosBundleId: 'com.example.studywithgary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFwkkPSsq_elg37RGwx4Ifi3R7FErMJeg',
    appId: '1:283681334251:web:1baed66adc2fa2f119efae',
    messagingSenderId: '283681334251',
    projectId: 'studywithgary-33612',
    authDomain: 'studywithgary-33612.firebaseapp.com',
    storageBucket: 'studywithgary-33612.firebasestorage.app',
  );
}
